// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "BETS_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RSS_vect_arma
List RSS_vect_arma(NumericVector yR, bool trend, bool seas, bool damped, int m, NumericMatrix init_statesR, NumericMatrix paramsR, bool return_residuals);
RcppExport SEXP _BETS_RSS_vect_arma(SEXP yRSEXP, SEXP trendSEXP, SEXP seasSEXP, SEXP dampedSEXP, SEXP mSEXP, SEXP init_statesRSEXP, SEXP paramsRSEXP, SEXP return_residualsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type yR(yRSEXP);
    Rcpp::traits::input_parameter< bool >::type trend(trendSEXP);
    Rcpp::traits::input_parameter< bool >::type seas(seasSEXP);
    Rcpp::traits::input_parameter< bool >::type damped(dampedSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type init_statesR(init_statesRSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type paramsR(paramsRSEXP);
    Rcpp::traits::input_parameter< bool >::type return_residuals(return_residualsSEXP);
    rcpp_result_gen = Rcpp::wrap(RSS_vect_arma(yR, trend, seas, damped, m, init_statesR, paramsR, return_residuals));
    return rcpp_result_gen;
END_RCPP
}
// build_design_and_c_batch
List build_design_and_c_batch(NumericVector yR, bool trend, bool seas, bool damped, int m, NumericMatrix paramsR);
RcppExport SEXP _BETS_build_design_and_c_batch(SEXP yRSEXP, SEXP trendSEXP, SEXP seasSEXP, SEXP dampedSEXP, SEXP mSEXP, SEXP paramsRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type yR(yRSEXP);
    Rcpp::traits::input_parameter< bool >::type trend(trendSEXP);
    Rcpp::traits::input_parameter< bool >::type seas(seasSEXP);
    Rcpp::traits::input_parameter< bool >::type damped(dampedSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type paramsR(paramsRSEXP);
    rcpp_result_gen = Rcpp::wrap(build_design_and_c_batch(yR, trend, seas, damped, m, paramsR));
    return rcpp_result_gen;
END_RCPP
}
// marginal_likelihood_rb
List marginal_likelihood_rb(arma::cube XtX_cube, arma::mat Xty_mat, arma::vec yty_vec, arma::vec eta0, arma::mat V0, double nu0, double psi0, int L, bool return_posterior);
RcppExport SEXP _BETS_marginal_likelihood_rb(SEXP XtX_cubeSEXP, SEXP Xty_matSEXP, SEXP yty_vecSEXP, SEXP eta0SEXP, SEXP V0SEXP, SEXP nu0SEXP, SEXP psi0SEXP, SEXP LSEXP, SEXP return_posteriorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type XtX_cube(XtX_cubeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xty_mat(Xty_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yty_vec(yty_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta0(eta0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V0(V0SEXP);
    Rcpp::traits::input_parameter< double >::type nu0(nu0SEXP);
    Rcpp::traits::input_parameter< double >::type psi0(psi0SEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< bool >::type return_posterior(return_posteriorSEXP);
    rcpp_result_gen = Rcpp::wrap(marginal_likelihood_rb(XtX_cube, Xty_mat, yty_vec, eta0, V0, nu0, psi0, L, return_posterior));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BETS_RSS_vect_arma", (DL_FUNC) &_BETS_RSS_vect_arma, 8},
    {"_BETS_build_design_and_c_batch", (DL_FUNC) &_BETS_build_design_and_c_batch, 6},
    {"_BETS_marginal_likelihood_rb", (DL_FUNC) &_BETS_marginal_likelihood_rb, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_BETS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
