// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RSS_vect_arma
List RSS_vect_arma(NumericVector yR, bool trend, bool seas, bool damped, int m, NumericMatrix init_statesR, NumericMatrix paramsR, bool return_residuals);
RcppExport SEXP _BETS_RSS_vect_arma(SEXP yRSEXP, SEXP trendSEXP, SEXP seasSEXP, SEXP dampedSEXP, SEXP mSEXP, SEXP init_statesRSEXP, SEXP paramsRSEXP, SEXP return_residualsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type yR(yRSEXP);
    Rcpp::traits::input_parameter< bool >::type trend(trendSEXP);
    Rcpp::traits::input_parameter< bool >::type seas(seasSEXP);
    Rcpp::traits::input_parameter< bool >::type damped(dampedSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type init_statesR(init_statesRSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type paramsR(paramsRSEXP);
    Rcpp::traits::input_parameter< bool >::type return_residuals(return_residualsSEXP);
    rcpp_result_gen = Rcpp::wrap(RSS_vect_arma(yR, trend, seas, damped, m, init_statesR, paramsR, return_residuals));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BETS_RSS_vect_arma", (DL_FUNC) &_BETS_RSS_vect_arma, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_BETS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
