# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RSS_vect_arma <- function(yR, trend, seas, damped, m, init_statesR, paramsR, return_residuals = FALSE) {
    .Call(`_BETS_RSS_vect_arma`, yR, trend, seas, damped, m, init_statesR, paramsR, return_residuals)
}

